MapTopic:              '/voxel_map'

InitMapFirst:            true

TargetTopic:            '/move_base_simple/goal'

DilateRadius:           0.1

VoxelWidth:              0.1

MapBound:                [-5.0, 5.0, -5.0, 5.0, 0.0, 2.0]

