Obstacles:
  - left_pos:
      - -1.6
      - 0.4
    length: 0.4
    width: 1.6
    height: 1.5

  - left_pos:
      - -1.2
      - 1.6
    length: 0.4
    width: 0.4
    height: 1

  - left_pos:
      - -0.4
      - 0.4
    length: 1.2
    width: 0.4
    height: 0.4

  - left_pos:
      - 0.4
      - 0.8
    length: 0.4
    width: 0.8
    height: 0.4

  - left_pos:
      - 1.2
      - 1.6
    length: 0.8
    width: 0.8
    height: 1.5

  - left_pos:
      - 1.2
      - -0.4
    length: 0.4
    width: 0.8
    height: 1.1

  - left_pos:
      - 0.0
      - -0.4
    length: 0.4
    width: 0.4
    height: 1.0

  - left_pos:
      - 0.0
      - -1.6
    length: 1.2
    width: 0.4
    height: 1.3

  - left_pos:
      - 0.4
      - -2
    length: 0.4
    width: 0.4
    height: 1.5

  - left_pos:
      - -1.6
      - -0.8
    length: 0.4
    width: 0.4
    height: 1.2

  - left_pos:
      - -1.2
      - -2
    length: 0.4
    width: 1.2
    height: 1.4


