Obstacles:
  - left_pos:
      - -1.4
      - 0.8
    length: 0.6
    width: 0.3
    height: 0.6

  - left_pos:
      - 0.55
      - 0.90
    length: 0.3
    width: 0.6
    height: 0.9

  - left_pos:
      - 0.85
      -  0.6
    length: 0.6
    width: 0.3
    height: 0.3

  - left_pos:
      - -1.9
      - -1.5
    length: 1.2
    width: 0.3
    height: 0.3

  - left_pos:
      - -0.7
      - -1.5
    length: 0.3
    width: 1.8
    height: 0.3

  - left_pos:
      - -1.9
      - 0.0
    length: 1.2
    width: 0.3
    height: 0.3

  - left_pos:
      - 0.6
      - -1.4
    length: 0.3
    width: 0.6
    height: 0.6

  - left_pos:
      - 1.2
      - -0.3
    length: 0.3
    width: 0.3
    height: 0.6